### PR TITLE
Change partion from Fat32 to Fat16

### LINKED ISSUE #2: Can't mount FAT32 partition from AmigaOS
For some reason, the FAT32 partition created by hdf2emu68 can't be mounted in AmigaOS (w/ FAT95). Reformatting that single partition from Windows fixes it.

A little thing makes it somehow different.

### PR DESCRIPTION
**Pull request by filemaster**
Fix #2 

Creates a Fat16 partition instead a Fat32, so both Amiga and MacOS can mount the first partition

### CODE REVIEW

**Comment by LemaruX** [comment]
Not sure this is needed.  Fat32 can already be read by Amigas and MacOS

**Comment by filemaster** [comment]
MacOS does not recognize the type `0x0C`, after changing the type to `0x0E` I could access to the partition with no changes in the OS... It was some time ago when I did this change, but I think I had some similar problem with Amiga OS 3.1.

**Comment by LemaruX** [comment]
> MacOS does not recognize the type `0x0C`, after changing the type to `0x0E` I could access to the partition with no changes in the OS... It was some time ago when I did this change, but I think I had some similar problem with Amiga OS 3.1.

~~We have been reading the fat32 partition on our Amigas since early PiStorm days. So it's not needed for that~~

Scrub that. I think this maybe that the fat32 created by this tool rather than fat32 in general (as other fat32 partitions created manually have been being mounted fine). The images created by this tool can't be opened in 7zip either (other images can without issue), so likely related. (Just noticed an issue has been raised for this too. Nice)

I feel this should maybe be added as an optional thing, not for all though

**Comment by TomCat666** [comment]
This needs to be tested on real amiga with pistorm... noone reported the fat32 partion created with this tool not being able to be mounted on the amiga...

**Comment by filemaster** [comment]
@TomCat666 I did not create the issue #2 , so at least we are 2 people with the same problem. 

I understand you do not want to use this as a general solution, so I can try to add some changes to do it optional as @LemaruX  suggested.

**Comment by TomCat666** [comment]
> MacOS does not recognize the type `0x0C`, after changing the type to `0x0E` I could access to the partition with no changes in the OS... It was some time ago when I did this change, but I think I had some similar problem with Amiga OS 3.1.

The 0x0E is overwritten later in the code when Fat32 partition is being formatted back to 0x0C ... so this change is basically ignored. Creating the IMG file with this change produces identical file.

If you want FAT16 image you need to change fmt_opt = {FM_FAT32 |    to fmt_opt = {FM_FAT |

**Comment by TomCat666** [comment]
On amiga also the FAT partition is not recognised. the only way to get it recognised is to mount the image on windows, format the partition.

**Comment by TomCat666** [comment]
> @TomCat666 I did not create the issue #2 , so at least we are 2 people with the same problem.
> 
> I understand you do not want to use this as a general solution, so I can try to add some changes to do it optional as @LemaruX suggested.

The change of 0x0C to 0x0E will do nothing, the resulting image still has 0x0C in the MBR since it is re-written by the FatFS system when it formats and builds the filesystem (fat32).

Try making an IMG file with 0x0C and 0x0E and compare the resulting images.

**Comment by filemaster** [comment]
You are right @TomCat666. Just cleaned a SD card and tried both options and the result is the same, and this time worked with no problem in Mac.

I created the PR back in March, and I don't remember if there is any other reason for this change... so I am going to close this PR. 

Thank you.

**Pull request closed without merging**
